# C:\Users\Dev Luis\Desktop\carnê\docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15 # Usar uma versão estável mais recente
    restart: always
    environment:
      POSTGRES_USER: devuser      # NOVO USUÁRIO, SEM CARACTERES ESPECIAIS
      POSTGRES_PASSWORD: devpassword # NOVA SENHA, SEM CARACTERES ESPECIAIS
      POSTGRES_DB: carnedb
    ports:
      - "5432:5432" # Mapeia a porta 5432 do container para a 5432 do seu PC
    volumes:
      - pgdata:/var/lib/postgresql/data # Persiste os dados do DB

volumes:
  pgdata: