"""Add parcela_fixa column to Carne model

Revision ID: 6ccedb5996a0
Revises: bd9f8555019f
Create Date: 2025-06-10 09:32:19.727692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ccedb5996a0'
down_revision: Union[str, None] = 'bd9f8555019f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carne', sa.Column('parcela_fixa', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carne', 'parcela_fixa')
    # ### end Alembic commands ###
