"""adicionar_coluna_data_venda_a_tabela_carne

Revision ID: f37e707c1454
Revises: 7c69526b016a
Create Date: 2025-06-04 17:28:05.309951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37e707c1454'
down_revision: Union[str, None] = '7c69526b016a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carne', sa.Column('data_venda', sa.Date(), nullable=True)) # Verifique se nullable=True é o desejado para dados existentes
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carne', 'data_venda')
    # ### end Alembic commands ###